apiVersion: apps/v1
kind: Deployment
metadata:
    name: go-hpa-deployment
spec:
    selector:
        matchLabels:
            app: go-hpa
    replicas: 1
    template:
        metadata:
            labels:
                app: go-hpa
        spec:
            containers:
              - name: go-hpa-container
                image: xpto1/go-hpa
                ports:
                  - containerPort: 80
                resources:
                    limits:
                        cpu: 100m
                        memory: 200Mi
                    requests:
                        cpu: 50m
                        memory: 100Mi